### ISSUE TITLE
Jitsi is not available in Plugins Registry 

### ISSUE THREAD

**Issue by naveensaini4u** [calvinckho/capacitor-jitsi-meet#1]
Hello,
When I have installed this plugin and after initializing it in my app and try to build it. It always gives the error mentioned below.

**"Type 'PluginRegistry' has no property 'Jitsi' and no string index signature."**

Please help to resolve this issue.

I'm using it in this way with ionic4.

**import { Component } from "@angular/core";
import { Plugins } from "@capacitor/core";
const { Jitsi } = Plugins;       // Here Jitsi is undefined or not available in PluginRegistry
@Component({
  selector: "app-home",
  templateUrl: "home.page.html",
  styleUrls: ["home.page.scss"]
})
export class HomePage {
  constructor() {
    console.log("Plugins", Plugins);
  }
  async getJitsi(){
    const result = await Jitsi.joinConference({
      roomName: 'room1', // room identifier for the conference
      url: 'https://meet.jit.si' // endpoint of the Jitsi Meet video bridge
    });
  }
}**

**Comment by calvinckho** [comment]
@naveensaini4u Thanks for using this plugin! You need to import 'capacitor-jitsi-meet' as well:

`
import { Component } from "@angular/core";
import { Plugins } from "@capacitor/core";
const { Jitsi } = Plugins;
**import 'capacitor-jitsi-meet';**
`
