### ISSUE TITLE
implemented to ios but entering meeting disconnected?

### ISSUE THREAD

**Issue by Boby** [calvinckho/capacitor-jitsi-meet#10]
Hi,

I implemented to the ionic 4 with ios app but when I tried accessing it it quickly close back and I saw a disconnect from the room

any missing steps?

**Comment by Taylorsuk** [comment]
I had this issue when I had setup my own Jitsi server. I tried using the URL `meet.jit.si` and it worked, this confirmed that the server setup was incorrect. 

Are you using a custom Jitsi server?

**Comment by Boby** [comment]
I am using custom server and both acts the same :( and it was working before with capacitor 2 with android base, but not the ios base

**Comment by Boby** [comment]
@Taylorsuk I can confirm that its the server, yeah I tested meet.jitsi and its working okay :) thanks once again!
