### ISSUE TITLE
Documentation issue iOS

### ISSUE THREAD

**Issue by maxfloden** [calvinckho/capacitor-jitsi-meet#102]
I am following this documentation https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/ios/README.md
However I found two things that you may want to check:

1.  Point 6 re Bitcode, I cannot find any Bitcode settings in my project, not sure if it is optional or something I should add? Xcode 15.2

2. When running my app it crashes and I get below errors in console. Suggestion is to add to documentation that Info.plist should contain NSCameraUsageDescription and NSMicrophoneUsageDescription keys with a explaination how the app uses this.

`This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSCameraUsageDescription key with a string value explaining to the user how the app uses this data.`

`This app has crashed because it attempted to access privacy-sensitive data without a usage description.  The app's Info.plist must contain an NSMicrophoneUsageDescription key with a string value explaining to the user how the app uses this data.`

**Comment by calvinckho** [comment]
Hi @maxfloden,

1. Bitcode is deprecated in Xcode 14 so step 6 is optional now. 
2. Agree. It's a good idea

The documentation needs to be updated to reflected these changes. Will you be able to submit a PR when you get a chance?
