### ISSUE TITLE
Capacitor 6.0 support

### ISSUE THREAD

**Issue by gasci** [calvinckho/capacitor-jitsi-meet#107]
Android SDK 34+ will be mandatory after August 2024. Do you have plans to upgrade this plugin?

**Comment by calvinckho** [comment]
Hi @gasci, I should have some free time next week and will try to work on it. I will give an update here when it is ready to be tested.

**Comment by calvinckho** [comment]
@gasci, the branch capacitor-6 is released and ready to be tested.

Can you install using the git branch and test it on the native devices? I tested it successfully on iOS. I do not have access to a physical Android at the moment so if you can let me know the outcome, it will be super helpful.

install using:

npm i git+ssh://git@github.com:calvinckho/capacitor-jitsi-meet#capacitor-6

**Comment by gasci** [comment]
I tested the v 6.0.0 on Android, too and it works. Thanks @calvinckho

**Comment by gasci** [comment]
Thank you for releasing v6.0.0
