### ISSUE TITLE
Possibility to set the password automatically

### ISSUE THREAD

**Issue by gianny80** [calvinckho/capacitor-jitsi-meet#108]
Hi,
Is there the possibility of setting the room password via API (or in another way) as is done for the web version?

For example, with the web version, when a user connects to a room, via API, it is possible to set the password in this way:

```
const api = new JitsiMeetExternalAPI(domain, options);

api.on('passwordRequired', function(event) {
   api.executeCommand('password', 'password-example');
});

api.on('participantRoleChanged', function(event) {
if (event.role === 'moderator') {
   api.executeCommand('password', 'password-example');
}
});

```

Thank you.

**Comment by calvinckho** [comment]
@gianny80 Unfortunately this feature is not yet supported by the mobile SDKs.
