### ISSUE TITLE
Showing Jitsi does not have web implementation.

### ISSUE THREAD

**Issue by coderaticebear** [calvinckho/capacitor-jitsi-meet#11]
I followed all the steps in Docs. Iam using Ionic 4 with angular , Cap version 1.5.2

**Comment by calvinckho** [comment]
that is correct. this plugin has no web implementation. To run Jitsi-meet on web app, you can use the Jitsi Meet API https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md
