### ISSUE TITLE
Video minimization

### ISSUE THREAD

**Issue by AlistairMRoss** [calvinckho/capacitor-jitsi-meet#110]
Has there been any enquiry into video minimization, particularly with IOS

**Comment by calvinckho** [comment]
@AlistairMRoss Jitsi said they were working on adding the native iOS PIP capability to the SDK, but unfortunately since almost 2 years now there is still no news on its release.

**Comment by calvinckho** [comment]
See this for more info on a non-native solution for iOS PIP: https://github.com/calvinckho/capacitor-jitsi-meet/issues/72

**Comment by AlistairMRoss** [comment]
@calvinckho 
Hi again, how much do you charge for the non-native implementation of PIP?

**Comment by calvinckho** [comment]
Before I can give you a quote, may I know which Ionic and Capacitor versions do you use? Also please DM me at ch235@cornell.edu for discussion on consultation related matters. Thanks.
