### ISSUE TITLE
Capacitor 6 branch incompatible with monaca.io online compiler

### ISSUE THREAD

**Issue by ItsSkynet** [calvinckho/capacitor-jitsi-meet#114]
i have been trying to import this plugin into their compiler and keep failing on debug/release builds.

this is the output of the console:

> [10:06:02] ✖ Updating iOS native dependencies with pod install - failed!
> [10:06:02] ✖ update ios - failed!
> [10:06:02] [error] Analyzing dependencies
> [10:06:02]         [!] CocoaPods could not find compatible versions for pod "CapacitorJitsiMeet":
> [10:06:02]         In Podfile:
> [10:06:02]         CapacitorJitsiMeet (from `../../node_modules/capacitor-jitsi-meet`)
> [10:06:02]         
> [10:06:02]         Specs satisfying the `CapacitorJitsiMeet (from `../../node_modules/capacitor-jitsi-meet`)` dependency were found, but they required a higher minimum deployment target.
> [10:06:02]         
> [10:06:02] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> [10:06:02] error Command failed with exit code 1.

Not sure if this can be fixed with using a downgraded version of the jitsi sdk or if the monaca.io service needs to update their build tools to allow changing the minimum deployment target for iOS. (If this is the case, then let this be a heads up for anybody else using their services and are trying to use this plugin as well)

**Comment by calvinckho** [comment]
Hi @ItsSkynet, seems like this is more an issue with monaca.io. I will close this since no action is required on our end. Perhaps you can create an issue on the monaca.io repo (asking them to allow changing the min deployment target for iOS) and then reference that issue here.
