### ISSUE TITLE
How can I listen to broadcasted events like chatMessageReceived?

### ISSUE THREAD

**Issue by nicolas-lescop** [calvinckho/capacitor-jitsi-meet#116]
Hi @calvinckho, 

First of all, I would like to say "thanks!" for this amazing plugin.

In my Ionic app, I need to synchronize the Jitsi chat with my own chat. I have tried the web version to listen to this event: [https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events/#outgoingmessage](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe-events/#outgoingmessage)

For iOS and Android SDKs, I need to listen to these kinds of events:
[https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk/#chat_message_received](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk/#chat_message_received)
[https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#chatmessagereceived](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk/#chatmessagereceived)

I'm a web developer and don't know how to listen to these kinds of events. Can you help me implement this?

Thanks a lot!

**Comment by calvinckho** [comment]
Hi @nicolas-lescop, the plugin's event listener currently does not listen to the #chat_message_received event. Your suggestion is feasible, but it is fairly time consuming to implement as our current event listener is not designed to return data object. You can either try to [tinker with it yourself](https://capacitorjs.com/docs/v2/plugins/android#returning-data-back), or wait for other contributors to respond and see if any of them also needs it and can add this feature for you. If no one can help you, you can [DM me](mailto:ch235@cornell.edu) and I can offer my consultation service to help you modify the plugin.

**Comment by nicolas-lescop** [comment]
Hi @calvinckho 

I try to implement it by himself, I can listen to the event and return data object.

Could you help me a little and tell me if there is a way to get the current user's Id participant? Because I find the `participantId` when I receive a message called `senderId`, but I can't easily know who the message belongs to.

Thanks

**Comment by calvinckho** [comment]
unfortunately I do not know how to find the user's Id participant. You may want to ask in the jitsi-meet github page or on other forums.

**Comment by calvinckho** [comment]
Good news. These event listeners have been added to the latest release.
