### ISSUE TITLE
Mute and Unmute Controls are not working

### ISSUE THREAD

**Issue by kumarmanishc** [calvinckho/capacitor-jitsi-meet#117]
This issue started happening after deployment of the fixes for #113..
We are able to join the meeting..
Audio and Videos buttons are showing but tap events are not triggering.. 

Have given all the permission required..
![Uploading image.jpg…]()

**Comment by calvinckho** [comment]
Can you take a look at this Jitsi issue and try to use the alpha server? https://github.com/jitsi/jitsi-meet/issues/14794#issuecomment-2157990406

At this moment Jitsi is still trying to solve the issue.

**Comment by calvinckho** [comment]
https://github.com/calvinckho/capacitor-jitsi-meet/issues/115#issuecomment-2252715264

I am closing this for now as it is an issue with the Jitsi SDK and not the plugin itself. We can reopen if it is unrelated to Jitsi's SDK.
