### ISSUE TITLE
Compatibility with Capacitor 2

### ISSUE THREAD

**Issue by rrlevy** [calvinckho/capacitor-jitsi-meet#13]
Hi @calvinckho 

This is an amazing module, I've used it in iOS but I miss the Android version (because we are using Capacitor 2).

I'd like to try to help updating the module for Capacitor 2 for Android. However, I stillI haven't worked with any Capacitor plugins or Native Android apps yet. I've just been developing Ionic apps with Cordova and Capacitor for the past 2 years. There are some other people hereat the company that could also help. 

Any tips on how should we start helping on that?

**Comment by calvinckho** [comment]
@rrlevy 1.3.9 is published which supports Capacitor 2, Xcode 1.3.1. 

If you have Xcode 1.4.1, you can try 1.4.0, which is also released. I don't have Xcode 1.4.1 so I can't test it yet. If you have Xcode 1.4.1+ please test it and let me know if it works. Thanks!

Thanks again for your desire to contribute!

**Comment by rrlevy** [comment]
Amazing!

I will definitely test it. I have installed Xcode 11.3 and 11.5. I will first test in on 11.5 and if it doesn't work, I'll try it on 11.4.1

**Comment by Taylorsuk** [comment]
`v1.4.1` is working well for me using XCode Version 11.5 (11E608c)

**Comment by Taylorsuk** [comment]
@calvinckho I think this is working well enough now, recommend we close this issue?

**Comment by calvinckho** [comment]
thanks @Taylorsuk!
