### ISSUE TITLE
facing issues with running on browser ionic preview, can you share steps to get this to work. 

### ISSUE THREAD

**Issue by sumeshd** [calvinckho/capacitor-jitsi-meet#15]
![Screenshot_98](https://user-images.githubusercontent.com/12375007/88817374-10e97600-d1db-11ea-9b90-0e3afbbf15bf.png)

**Comment by Taylorsuk** [comment]
This Capacitor plugin is for native use on iOS and Android. I've not looked at it for a while, however I don't believe it has a web implementation. 

Also, from your error, it doesn't look like that is coming from this plugin. You should get a graceful error if you try to connect to a conference on a Web App.

**Comment by calvinckho** [comment]
For web implementation, see the Jitsi Meet API doc (https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md)

**Comment by calvinckho** [comment]
Thanks @Taylorsuk. the console now logs the proper instructions to implement Jitsi Meet Web API. It will be available in the next release.
