### ISSUE TITLE
How to set configOverwrite or setFeatureFlag to remove the invite button?

### ISSUE THREAD

**Issue by dcontreras87** [calvinckho/capacitor-jitsi-meet#16]
This plugin works really well, thank you very much for sharing it. 

I would like to know if it's possible to use the setFeatureFlag to remove the "invite" button? (And also removing other interface/configuration params as the recording button, etc). When using the official iframe API for websites there is a configOverwrite param for this, but I'm not able to find how to make it work on this plugin for Android.

Any guidance to accomplish this will be highly appreciated.

**Comment by calvinckho** [comment]
I saw that the setFeatureFlag is indeed available in the current SDK but I have not added it to the plugin yet.

I'm keeping this here for my reference when I add this in the next release:
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js

**Comment by dcontreras87** [comment]
Great! Thank you for that!! 

I know probably I should not ask this, but the answer is very important for my project planning. Is there any approximate date for next release? 

Once again, thank you for this amazing plugin!

**Comment by calvinckho** [comment]
Good news, 1.4.2 is released!

I have added the inviteEnabled flag to the plugin. See README for usage. Please try and upgrade to 1.4.2 to test it. It works on my Android device, but I don't have Xcode 14 so can't test the new feature on iOS yet.

**Comment by calvinckho** [comment]
I have using Xcode 11.16 and can confirm that the inviteEnabled flag is working in 1.4.2+.

**Comment by dcontreras87** [comment]
Thank you very much!!! I really appreciate all your time to give us this excellent plugin!!!
