### ISSUE TITLE
Is there a way to reduce the app size? 

### ISSUE THREAD

**Issue by dmastag** [calvinckho/capacitor-jitsi-meet#17]
I was wondering about the app size. Since this plugin ads more than 30mb, but the official jitsi meet plugin is less than 10mb in size. (Though it becomes bigger once its loaded) 

Is there something we can do to decrease the app size? Like having some of the sdk downloaded after loading for the first time.

**Comment by dmastag** [comment]
My bad, jitsi official on the play store is 29MB

But I was analyzing the resulted Build and looked at this.
![image](https://user-images.githubusercontent.com/5745805/89096264-9baaba80-d3ff-11ea-87e4-fb66001cb953.png)

Maybe we can make 4 builds per type and upload to play store like that. And remove the unused types.

**Comment by calvinckho** [comment]
The Android App Bundle feature is used to reduce download size. Have you tried it? 

https://developer.android.com/guide/app-bundle/

**Comment by dmastag** [comment]
Yes, that one is an .aab file
Was just thinking if it can be even smaller. 

Hard to justify to have users add 30MB to the original App we have.
