### ISSUE TITLE
issue with android

### ISSUE THREAD

**Issue by sumeshd** [calvinckho/capacitor-jitsi-meet#19]
I have followed instructions as I read MD and followed all 3 steps.
Then followed up with the Jitsi Meet android deployment documentation. However I see issues happening can you help me build this right. 

![Screenshot_100](https://user-images.githubusercontent.com/12375007/89070759-15588f00-d393-11ea-89c7-cb17124a81d5.png)

**Comment by calvinckho** [comment]
Duplicate of #18
