### ISSUE TITLE
Issue with ios build 

### ISSUE THREAD

**Issue by gmarec** [calvinckho/capacitor-jitsi-meet#2]
Hi, 

Thanks for this plugin @calvinckho , I've seen you upgraded Android to SDK 2.2.2 but not ios SDK, still stuck with 1.2x, why ?
With Xcode 10.2 I can't build for ios with an error swift compiler 5.0.1 can't import 4.2.1 module ... I try to force swift to be on 4.2.1, but it still hangs. Do you have any idea ?

Thanks

**Comment by calvinckho** [comment]
I had been wanting to upgrade the iOS SDK but didn’t have time to do it. As soon as I got it done I will publish the code. Thanks!

**Comment by calvinckho** [comment]
the iOS SDK is upgraded to 2.4.2 so it works with Swift 5 now. I will close this issue and you are welcomed to reopen it if you encounter other problems.
