### ISSUE TITLE
Picture in Picture not working

### ISSUE THREAD

**Issue by dmastag** [calvinckho/capacitor-jitsi-meet#20]
Hi @calvinckho 
I got this working on android but without picture in picture.
I was able to get it to work after adding to

https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/android/capacitor-jitsi-meet/src/main/AndroidManifest.xml#L5

With the following
```
android:supportsPictureInPicture="true"
```

considering that it is in the original jitsi meet repo, see :

https://github.com/jitsi/jitsi-meet/blob/master/android/app/src/main/AndroidManifest.xml#L19

and

https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/AndroidManifest.xml#L36

I was wondering if I should make a pull request or if this was intentional and there is a step in the Android implementation that I do not correctly understand.

Any pointers would be appreciated.

**Comment by calvinckho** [comment]
thanks @dmastag. This is a great enhancement.

**Comment by dmastag** [comment]
You're welcome.
Hopefully you can push a new release to npm soon 😃

**Comment by calvinckho** [comment]
The PIP is working, unfortunately, there are a few issues:

1) While you are in a Jitsi call, when hiding app and PIP is activated, it stops the Jitsi call and rejoins it. The disruption is quite unpleasant.
2) While the PIP window is on, when maximizing the PIP to return to full screen, the first time around it works. But the second time it crashes.

@dmastag do you notice the same issues?

**Comment by dmastag** [comment]
Hi @calvinckho 
I didn't check that deep yet.

Maybe if I have some time next week

**Comment by calvinckho** [comment]
#67 https://github.com/calvinckho/capacitor-jitsi-meet/issues/67#issuecomment-1059713128
