### ISSUE TITLE
How can we enable CALL_INTEGRATION?

### ISSUE THREAD

**Issue by sumeshd** [calvinckho/capacitor-jitsi-meet#22]
Firstly, thank you for maintaining this repository. It is of immense help. 

I am looking to make call kit this work with call kit on both iOS and android, how could I make that happen, as I could not find any reference to CALL_INTEGRATION in the repository.

**Comment by calvinckho** [comment]
call integration is enabled by default. https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js

On my iOS app, it is logging the Jitsi outbound calls on the call history. But it is not logging on the android call history. You may want to create an issue on Jitsi Github page to ask them for more documentation on the CallKit and ConferenceService integration. https://github.com/jitsi/jitsi-meet/issues?q=
