### ISSUE TITLE
What is the difference between 1.4.2 and 1.3.12

### ISSUE THREAD

**Issue by dmastag** [calvinckho/capacitor-jitsi-meet#23]
I am seeing 2 versions with 1.3.12 being the latest.
Mind letting us know what the difference is?

**Comment by calvinckho** [comment]
1.4.2: requires Capacitor 2.0+, Xcode 1.4.1+
1.3.12: requires Capacitor 2.0+, Xcode 1.3.1.

**Comment by calvinckho** [comment]
see documentation for more info
