### ISSUE TITLE
[Info] iOS will not be approved in China

### ISSUE THREAD

**Issue by dmastag** [calvinckho/capacitor-jitsi-meet#24]
Hi All,
Wanted to let you all know that when I tried to submit an app with this Plugin I got Binary rejected.
Here are the details:

![image](https://user-images.githubusercontent.com/5745805/89597775-41897980-d885-11ea-8df3-ebc3ef0438b9.png)

**Comment by dmastag** [comment]
Some additional info I found regarding disabling this:

https://github.com/jitsi/jitsi-meet/issues/3152

https://github.com/jitsi/jitsi-meet/issues/4970

I have not tried this yet and just removed Apple from my List of Available countries.

**Comment by calvinckho** [comment]
It should be as simple as adding a property for JMCallKitProxy.enabled in our plugin. I'll work on it and should have a new release by this weekend.

https://github.com/jitsi/jitsi-meet/issues/4970#issuecomment-609360056

**Comment by dmastag** [comment]
Awesome

Am just thinking how I would now that someone is using the Chinese App Store to have this problematically turned off.

Looked at this, but it seems like a dirty workaround
https://stackoverflow.com/questions/51053847/can-i-know-the-region-of-ios-app-store-that-my-app-downloaded-from

**Comment by calvinckho** [comment]
latest version is released

1. it detects the NSLocale.current.countryCode and turns off CallKit if user is located in China
2. You can try to resubmit the app and explain this adaptation.

**Comment by dmastag** [comment]
That was fast, thanks!
I'll try to resubmit it

**Comment by calvinckho** [comment]
@dmastag any update on this? Did they approve it for China Appstore?

**Comment by dmastag** [comment]
Yes, they did.
Or maybe they didn't check after I submitted an update.

Based on experience you never really know with Apple regarding the Review progress. Sometimes they'll complain in the 10th update I submit next year regarding something I did this year.

**Comment by calvinckho** [comment]
sounds good. I'll close this for now then.

**Comment by ankit0812** [comment]
@dmastag Did this reappear anytime later or the check using the Locale worked fine?

**Comment by dmastag** [comment]
No Problems yet even though I had several updates submitted since
