### ISSUE TITLE
Could not find or use auto-linked framework 'JitsiMeet' (iOS)

### ISSUE THREAD

**Issue by Avareto** [calvinckho/capacitor-jitsi-meet#29]
When I try to create an Archive build (Product -> Archive) Xcode build fails with "Could not find or use auto-linked framework 'JitsiMeet'". 

Running and deploying the App in Simulator works fine without any errors.  
Any idea?

Showing All Messages
Ld /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CapacitorJitsiMeet.framework/CapacitorJitsiMeet normal (in target 'CapacitorJitsiMeet' from project 'Pods')
    cd /Users/avaretosoftware/frontend/avaretoapp/ios/App/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios11.0 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.0.sdk -L/Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorJitsiMeet -F/Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorJitsiMeet -F/Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/Capacitor -F/Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorCordova -F/Users/avaretosoftware/frontend/avaretoapp/ios/App/Pods/JitsiMeetSDK/Frameworks -filelist /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/CapacitorJitsiMeet.build/Objects-normal/arm64/CapacitorJitsiMeet.LinkFileList -install_name @rpath/CapacitorJitsiMeet.framework/CapacitorJitsiMeet -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/CapacitorJitsiMeet.build/Objects-normal/arm64/CapacitorJitsiMeet_lto.o -fembed-bitcode -Xlinker -bitcode_verify -Xlinker -bitcode_hide_symbols -Xlinker -bitcode_symbol_map -Xlinker /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/BuildProductsPath/Release-iphoneos/CapacitorJitsiMeet -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/CapacitorJitsiMeet.build/Objects-normal/arm64/CapacitorJitsiMeet.swiftmodule -framework Capacitor -framework Foundation -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/CapacitorJitsiMeet.build/Objects-normal/arm64/CapacitorJitsiMeet_dependency_info.dat -o /Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-asgwkjcbcyekhxclqlvowinmxpgc/Build/Intermediates.noindex/ArchiveIntermediates/App/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/CapacitorJitsiMeet.framework/CapacitorJitsiMeet

ld: warning: Could not find or use auto-linked framework 'JitsiMeet'
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_JitsiMeetView", referenced from:
      objc-class-ref in JitsiMeetViewController.o
  "_OBJC_CLASS_$_JitsiMeetConferenceOptions", referenced from:
      objc-class-ref in JitsiMeetViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by calvinckho** [comment]
@Avareto can you provide me with more info? which capacitor-jitsi-meet version and Xcode version?

**Comment by Avareto** [comment]
capacitor-jitsi-meet: ^1.5.3 
XCode 12

**Comment by calvinckho** [comment]
just to clarify, have you followed these steps: https://github.com/calvinckho/capacitor-jitsi-meet/blob/HEAD/ios/README.md#usage?

**Comment by Avareto** [comment]
Yes. I created a very simple ionic project to minmal side effects. I can build it for simulator and any device, but it fails when I try to build for "Any device (arm64)". This is need to deploy the App to the AppStore. Maybe some architecture properties need to ajusted. See the error message: 

`.../Library/Developer/Xcode/DerivedData/App-bjilqrwkatrdisbpgijbdhxygxhr/Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework/Capacitor' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/avaretosoftware/Library/Developer/Xcode/DerivedData/App-bjilqrwkatrdisbpgijbdhxygxhr/Build/Products/Debug-iphoneos/Capacitor/Capacitor.framework/Capacitor' for architecture arm64`

**Comment by calvinckho** [comment]
Please follow the instructions to disable bitcode in the above link.

**Comment by Avareto** [comment]
That was exctly the problem. Compiling for AppStore (any/generic device, Product=>Archiv) only worked for me with XCode 12.1 when I do the following:
...
3. Turn off Bitcode in the app target as well as the pod targets. In xcode Project Navigator,
**i. App -> Targets -> App -> Build Settings -> Enable Bitcode -> No**
ii Pods -> Targets -> CapacitorJitsiMeet -> Build Settings -> Enable Bitcode -> No
4. ...

**Comment by calvinckho** [comment]
Does it solve your issue?

**Comment by Avareto** [comment]
Yes!
