### ISSUE TITLE
undefined is not an object on iOS

### ISSUE THREAD

**Issue by tonymccallie** [calvinckho/capacitor-jitsi-meet#3]
I'm trying to set this up in my Ionic 4/Capcitor app.

Here's how I have it implemented:
```
import { MessagesService } from './../../services/messages.service';
import { ModalController, NavParams } from '@ionic/angular';
import { Component, OnInit } from '@angular/core';
import { Plugins } from '@capacitor/core';
import 'capacitor-jitsi-meet';

const { Jitsi } = Plugins;

@Component({
	selector: 'app-videochat',
	templateUrl: './videochat.page.html',
	styleUrls: ['./videochat.page.scss'],
})
export class VideochatPage implements OnInit {
	conversationId: string;
	remoteCalls: any = [];

	constructor(
		private modal: ModalController,
		private navParams: NavParams,
		private msg: MessagesService
	) {
		this.conversationId = this.navParams.get('conversationId');
		console.warn('VideoChatModalLoaded', this.conversationId);
		this.init();
	}

	async init() {
		const result = await Jitsi.joinConference({
			roomName: 'room1', // room identifier for the conference
			url: 'https://meet.jit.si', // endpoint of the Jitsi Meet video bridge
			channelLastN: '-1', // default -1. see config.js for more info on the last n feature
			startWithAudioMuted: true, // start with audio muted
			startWithVideoMuted: false // start with video muted
		});
	}
}
```

And in XCode, the error I'm getting is:
`ERROR Error: Uncaught (in promise): TypeError: undefined is not an object (evaluating 'Jitsi.joinConference')`

Any ideas? Thanks

**Comment by calvinckho** [comment]
1. First make sure the project got built successfully with ionic. Can you verify the capacitor-jitsi-meet is installed correctly in /node-module directory?

2. You need to do 'npx cap sync' so the plugin is installed natively. Have you followed the iOS steps listed here: https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/ios/README.md?

**Comment by tonymccallie** [comment]
Ok, I was massing the `npx cap sync` step, but that runs into a new error.

capacitor-jitsi-meet is installed on /node_modules

I did go through all those steps and I'm still getting this error:
```
Module compiled with Swift 4.2.1 cannot be imported by the Swift 5.1 compiler: /Users/tonymccallie/Sites/AVA/ios/App/Pods/JitsiMeetSDK/jitsi-meet-ios-sdk-releases-1.21.1/Frameworks/JitsiMeet.framework/Modules/JitsiMeet.swiftmodule/arm64.swiftmodule
```

But, my Pods->Targets->Capacitor->Build Settings is set to 4.2. 
When I look at Pods->Targets->JitsiMeetSDK->Build settings, it says SWIFT_VERSION 5.0

I'm in XCode 11.1 on macOS Catalina. Could that be the problem?

Thanks for helping me look into this.

**Comment by tonymccallie** [comment]
Also, I did do a Product->Clean Build Folder

**Comment by tonymccallie** [comment]
An update on this. I tried compiling with XCode 10 on Ionic AppFlow and got the same errors.

**Comment by tonymccallie** [comment]
![Screen Shot 2019-11-08 at 4 08 16 PM](https://user-images.githubusercontent.com/35459/68516713-026cc000-0242-11ea-8b8a-cae56cdfd6f2.png)

**Comment by calvinckho** [comment]
I will release a new build that uses the newest Jitsi-meet iOS SDK which should work with Swift 5.0.

**Comment by calvinckho** [comment]
1.3.5 is released and the iOS SDK is upgraded to 2.4.2 so it works with Swift 5 now. Please give it a try and let me know.

**Comment by tonymccallie** [comment]
I was still unable to get this to work on my system, so I created a new project to make sure there was no other conflicts:
https://github.com/tonymccallie/jitsi

All I did was a new Ionic 4 app and then walk through your iOS steps listed here:
https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/ios/README.md

and these are the same errors I'm getting in both apps:
<img width="1031" alt="Screen Shot 2019-11-12 at 3 31 20 PM" src="https://user-images.githubusercontent.com/35459/68716474-8637ec80-0561-11ea-983e-14c07a720acb.png">

**Comment by tonymccallie** [comment]
Is there any information I can give that will help to find the culprit? Thanks for your time.

**Comment by calvinckho** [comment]
Looks like your project is still using the old SDK. Try to do ‘pod install’ inside the iOS directory.

**Comment by calvinckho** [comment]
One more thing to try. Do ‘npx cap update’ in the Ionic project directory and follow the warnings which should tell you about updating the pod repo on your machine.

**Comment by tonymccallie** [comment]
Here's the result of `npx cap update`
```
tonys-macbook:AVA tonymccallie$ npx cap update
✔ Updating Android plugins in 76.10ms
  Found 2 Capacitor plugins for android:
    capacitor-fcm (0.1.0)
    capacitor-jitsi-meet (1.3.5)
  Found 8 Cordova plugins for android
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-ionic (5.3.1)
    cordova-plugin-nativestorage (2.3.2)
    cordova-plugin-whitelist (1.3.4)
⠹ update android  Found 3 incompatible Cordova plugins for android, skipped install
    cordova-plugin-ionic-webview (4.1.2)
    cordova-plugin-splashscreen (5.0.3)
    cordova-plugin-statusbar (2.4.3)
✔ update android in 239.45ms
✔ Updating iOS plugins in 69.62ms
  Found 2 Capacitor plugins for ios:
    capacitor-fcm (0.1.0)
    capacitor-jitsi-meet (1.3.5)
  Found 7 Cordova plugins for ios
    cordova-plugin-camera (4.1.0)
    cordova-plugin-device (2.0.3)
    cordova-plugin-file (6.0.2)
    cordova-plugin-file-transfer (1.7.1)
    cordova-plugin-geolocation (4.0.2)
    cordova-plugin-ionic (5.3.1)
    cordova-plugin-nativestorage (2.3.2)
✔ Updating iOS native dependencies with "pod install" (may take several minutes) in 6.77s
  Found 4 incompatible Cordova plugins for ios, skipped install
    cordova-plugin-ionic-webview (4.1.2)
    cordova-plugin-splashscreen (5.0.3)
    cordova-plugin-statusbar (2.4.3)
    cordova-plugin-whitelist (1.3.4)
⠼ update ios[warn] Plugin cordova-plugin-ionic requires you to add 
  <key>IonApi</key>
  --truncated--
  <string>$MIN_BACKGROUND_DURATION</string>
 to your Info.plist to work
✔ update ios in 6.97s
✔ update web in 11.68μp
Update finished in 7.227s
```

and `pod install`
```
tonys-macbook:App tonymccallie$ rm -fr Pods
tonys-macbook:App tonymccallie$ pod install
Analyzing dependencies
Downloading dependencies
Installing Capacitor (1.3.0)
Installing CapacitorCordova (1.3.0)
Installing CapacitorFcm (0.1.0)
Installing CapacitorJitsiMeet (1.3.5)
Installing CordovaPlugins (1.2.1)
Installing Firebase (6.12.0)
Installing FirebaseAnalytics (6.1.5)
Installing FirebaseAnalyticsInterop (1.4.0)
Installing FirebaseCore (6.3.3)
Installing FirebaseCoreDiagnostics (1.1.1)
Installing FirebaseCoreDiagnosticsInterop (1.1.0)
Installing FirebaseInstanceID (4.2.7)
Installing FirebaseMessaging (4.1.8)
Installing GoogleAppMeasurement (6.1.5)
Installing GoogleDataTransport (3.0.1)
Installing GoogleDataTransportCCTSupport (1.2.1)
Installing GoogleUtilities (6.3.1)
Installing JitsiMeetSDK (2.4.2)
Installing Protobuf (3.10.0)
Installing nanopb (0.3.9011)
Generating Pods project
Integrating client project
Pod installation complete! There are 5 dependencies from the Podfile and 20 total pods installed.
```

I then did a Product->Clean and cleared out the Derived Data and I'm getting the exact same errors. Are there any log files I could post that might help? 

I also ran this at Ionic AppFlow with XCode 10 and XCode 11 with no success.

**Comment by tonymccallie** [comment]
I found this issue, but it seems to be resolved. Not sure if it's helpful or not:
https://github.com/jitsi/jitsi-meet/issues/4666

**Comment by calvinckho** [comment]
<img width="1280" alt="Screen Shot 2019-11-13 at 3 45 35 PM" src="https://user-images.githubusercontent.com/23274587/68814068-b00a1580-062c-11ea-9287-beb41f17d85e.png">

I compiled your project and was able to run it on my iOS simulator. It loads everything successfully, including the Capacitor Jitsi plugin. Sorry I really don't know what caused your errors.

**Comment by calvinckho** [comment]
you may want to take a look at the list of Pods on the left of my Xcode panel and make sure you have all the pods loaded correctly.

**Comment by tonymccallie** [comment]
What version of MacOS and XCode are you on?

**Comment by calvinckho** [comment]
macOS Mojave 10.14.6, Xcode 11.2.1

**Comment by tonymccallie** [comment]
Ok... after updating my XCode (which I thought was updated but apparently was having system issues) I was able to get this to compile on a simulator, but not on my device.

I get the following compile error:
```
'/Users/tonymccallie/Sites/AVA/ios/App/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/tonymccallie/Sites/AVA/ios/App/Pods/JitsiMeetSDK/Frameworks/JitsiMeet.framework/JitsiMeet' for architecture arm64
```
I set the project, JitsiMeetSDK, and Capacitor all in different combinations of disabling bitcode... all to no avail. 

Are you able to compile to your device?

**Comment by tonymccallie** [comment]
I get the same error when I try to archive to use TestFlight

**Comment by tonymccallie** [comment]
I found it. You have to set bitcode no on Target->CapacitorJitsiMeet. Thanks for your help!

**Comment by calvinckho** [comment]
@tonymccallie Great. I'm glad it is working now. I'll close this since the original issue has been resolved. Good luck with your project!
