### ISSUE TITLE
Question: User information

### ISSUE THREAD

**Issue by Avareto** [calvinckho/capacitor-jitsi-meet#31]
Hi Calvin!

I gess the current implemenation dosen't support adding user information to the options (?) 
I think it would be very common that an app has user information available in this context and it would be very convinient to simply add them to the options on entering a meeting room. As far as I know, the Jitsi Meet Api for the web support user information:
`Jitsi.joinConference({
...,
userInfo: {
        email: 'email@jitsiexamplemail.com',
        displayName: 'John Doe'
      },
...
});`
Because I am not an android and ios expert, my question is: Do you think  this can be simply added to extend the capacitor (ios & android) implemenation to support userInfo? If yes, can you please point me to the code where this needs to be added/changed?

For Android there seems to be an option property for userInfo: 
` public Builder setUserInfo(JitsiMeetUserInfo userInfo) {
            this.userInfo = userInfo;
            return this;
        }
`
https://github.com/jitsi/jitsi-meet/blob/master/android/sdk/src/main/java/org/jitsi/meet/sdk/JitsiMeetConferenceOptions.java#L258

Regards
Andreas

**Comment by calvinckho** [comment]
Hi @Avareto, I am looking at the SDK code. You are right, I see that userInfo is now available in the SDK so we should be able to add it as a param in the plugin.

I will release a new version that supports it in a few days. Stay tuned.

**Comment by Avareto** [comment]
Just as a note: The property userInfo supports an avatar url as well. So passing the avatar url as well would be nice because in an app you usually have the picture of the current user available. Not sure if pointing to the devices storage (filesystem url like file://) is supported or/and urls to external storage (like https://.....).

**Comment by Avareto** [comment]
Hi @calvinckho, any news on this?

**Comment by calvinckho** [comment]
Not yet but will likely get it done next week.

**Comment by Avareto** [comment]
Hi @calvinckho are you still planning to implement this? Can I help you in any way?

**Comment by calvinckho** [comment]
sorry @Avareto I assigned my colleague to work on it but he is having issues.

**Comment by aguilalibre** [comment]
I am also very very interested in this function. ¡¡ Thank you very much for all the work and effort !!

**Comment by calvinckho** [comment]
I'm excited to share that 1.5.6 is released which now includes the displayName, email, and avatarURL params. Please consult the [readme](https://github.com/calvinckho/capacitor-jitsi-meet) for details on these new params.

**Comment by Avareto** [comment]
New feature avatarUrl, email and displayName not working on iOS. Currently it seems to works for Android only !!

**Comment by Avareto** [comment]
I looked into the repro and it seems that you only added this feature to Android. There are no changes for iOS!
Is it possible that you accidentally forgot to commit the iOS/Swift changes?
