### ISSUE TITLE
Add android screen-sharing support

### ISSUE THREAD

**Issue by knutsur** [calvinckho/capacitor-jitsi-meet#32]
Hi Calvin,

It seems that support for android screen sharing is merged to master.
 
https://github.com/jitsi/jitsi-meet/commit/9a35026d6a10418436128e59350e10fa2b382070

It would be great to have this feature in your awesome plugin! 🥇 

Any estimate when this will be implemented?

**Comment by calvinckho** [comment]
@knutsur thanks for the heads up. 1.5.5 is just released. I tested it on my android and screen sharing is working!
