### ISSUE TITLE
Upgrade for Xcode 12.2

### ISSUE THREAD

**Issue by gcvetkoski** [calvinckho/capacitor-jitsi-meet#33]

**Comment by gcvetkoski** [comment]
Hi,

Did you like to rebuild for xcode 12.2 Jisti meet SDK do that yesterday.

Tnx a lot

**Comment by calvinckho** [comment]
Thanks @gcvetkoski for the heads up. I just released 1.5.5 that uses Jitsi 12.2.0 mobile SDK.
