### ISSUE TITLE
Expand plugin

### ISSUE THREAD

**Issue by gcvetkoski** [calvinckho/capacitor-jitsi-meet#34]
I think you should expand this plugin with following:

1. Subject, displayName...
2. Leave meeting function

**Comment by calvinckho** [comment]
thanks @gcvetkoski I think those are great suggestions. I see that subject is a variable available in the SDK. displayName will be included in userInfo which is currently being worked on. 

The leave meeting function is actually quite useful. Let me do some research and see if we can terminate the SDK view on the plugin level.

**Comment by gcvetkoski** [comment]
Any news when we will expect new version?

**Comment by calvinckho** [comment]
We are a bit behind with adding the userInfo. I should have more time this week to work on it.

**Comment by calvinckho** [comment]
#31 I'm excited to share that 1.5.6 is released which now includes the displayName, email, and avatarURL params. Please consult the readme for details on these new params.

**Comment by calvinckho** [comment]
@gcvetkoski I'm going to close this for now because 1) I have added the displayName, email, avatarURL to the plugin, and 2) the SDK does not yet support ending call algorithmically. Please reopen it when the SDK supports it. Thanks.

**Comment by creativearish** [comment]
#43 If anybody is still looking for manual leave conference option.

**Comment by calvinckho** [comment]
the manual leaveConference() method is added to both iOS and android plugins. credits to @creativearish for adding the iOS code.
