### ISSUE TITLE
Share Screen

### ISSUE THREAD

**Issue by GustavDjavulen** [calvinckho/capacitor-jitsi-meet#35]
Hi.

The implementation was a success, but it happens that when I want to share a screen, the users who see it cannot see anything.

**Comment by calvinckho** [comment]
What android device are you using to share screen? I tested it on a Samsung S7 and it worked fine. You may want to file an issue in the jitsi repo since this feature is built in their SDK.

**Comment by GustavDjavulen** [comment]
It's a HUAWEI P30 lite, i'll check the jitsi repo

**Comment by GustavDjavulen** [comment]
> It's a HUAWEI P30 lite, i'll check the jitsi repo

I did tests with, "Motorola Z3, Android 9", "Motorola one, android 10", "Xiaomi redmi note 8, Android 10" and the problem persists.

**Comment by calvinckho** [comment]
@GustavDjavulen, any update on reporting this bug in the jitsi repo? Are others encountering the same bug?

**Comment by timmyrosen** [comment]
@calvinckho Screen share doesn't work for me either. Tried on an iPhone X and OnePlus 8 Pro. Screen just goes dark

**Comment by calvinckho** [comment]
Hey guys, I am still able to share screen on my Samsung S7 and iPhone X (simulator). So I can't reproduce your issue.

For Android, I found this article: https://sendbird.com/developer/tutorials/screen-sharing-android for giving the foreground permission. Maybe @GustavDjavulen @timmyrosen can give it a try? Also check your log and see if you have the same warning as in [here](https://stackoverflow.com/questions/64841767/is-it-possible-to-do-screen-recording-without-using-foreground-service-for-andro).
