### ISSUE TITLE
Error on build android

### ISSUE THREAD

**Issue by henrywongkar** [calvinckho/capacitor-jitsi-meet#36]
* What went wrong:
Could not determine the dependencies of task ':capacitor-jitsi-meet:generateDebugRFile'.
> Could not resolve all task dependencies for configuration ':capacitor-jitsi-meet:debugCompileClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:2.11.0.
     Required by:
         project :capacitor-jitsi-meet

Anything I miss?

**Comment by calvinckho** [comment]
have you read through and followed the android deployment instructions? 

https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/android/README.md

**Comment by henrywongkar** [comment]
Thanks for pointing out. Now build is successful. I'm closing this issue
