### ISSUE TITLE
Critical help request - Hide some buttons from the options menu

### ISSUE THREAD

**Issue by aguilalibre** [calvinckho/capacitor-jitsi-meet#37]
Hello Calvin! Thanks for your great work with this plugin. I would like to make the following question, is there a way to hide from UI or via featureFlag the following buttons?

![20210116_080423](https://user-images.githubusercontent.com/17222823/104813964-f8ddd100-57d1-11eb-9b25-6923bd7898c7.jpg)

The buttons you see marked as red are: Enable lobby mode, silence all and help.  Its critical for my project to get these three buttons hidden (at least two of them, enable lobby mode and silence all). I will be thankful if you can help me out as I can't go live because of this.

Once again, thank you very much for your time

**Comment by calvinckho** [comment]
I will take a look today. Will get back to you.

**Comment by calvinckho** [comment]
@aguilalibre I don't see a way to disable the menu options in the SDK yet. Here is a list of features that we can further customize but I do not see those menu options listed: https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.js

**Comment by calvinckho** [comment]
@aguilalibre, I filed a question on the jitsi forum and am waiting for the Jitsi developers for response. I will get back to you as soon as I hear any update from them. https://community.jitsi.org/t/hiding-certain-controls-on-ios/17670/15?u=calvinckho

**Comment by calvinckho** [comment]
Hi @aguilalibre, I have done some more research into the [Jitsi source code](https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/native/OverflowMenu.js). Currently, the published SDK offers no way to hide those options. My suggestion is to have your team modify the above file by commenting out those menu options, then build and use your own SDK artifacts/binaries by following [these steps](https://github.com/jitsi/jitsi-meet/blob/master/react/features/toolbox/components/native/OverflowMenu.js). I am going to close this for now as it answers your initial question about available params supported by the published SDK. Any further SDK customization is beyond the scope of this plugin. If you need further help, you can DM me.
