### ISSUE TITLE
web plugin

### ISSUE THREAD

**Issue by lsmod** [calvinckho/capacitor-jitsi-meet#4]
Hello,

I got this error in browser `uncaught exception: Jitsi does not have web implementation.`.

Works just fine on android (havn't test on iOS yet). Nice plugin by the way :+1:

**Comment by calvinckho** [comment]
Thanks for using this plugin. This plugin (and its underlying SDK) was written for iOS and Android only. For web implementation, please consult https://github.com/jitsi/jitsi-meet/blob/master/doc/api.md.
