### ISSUE TITLE
iOS crash on starting app

### ISSUE THREAD

**Issue by henry-wonder** [calvinckho/capacitor-jitsi-meet#40]
Not sure what could be the problem, but the app cannot start in iOS. It crashes immediately.
Can you share what is your Podfile looks like after you follow step no.3 and 4 in https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/ios/README.md. Thanks

**Comment by calvinckho** [comment]
Make sure you are using Xcode 12.2. The plug-in is not ready for 12.3 yet as the latest SDK has not been released by Jitsi yet.

**Comment by henry-wonder** [comment]
It would be really helpful if you can paste here the Podfile looks like. Thanks

**Comment by calvinckho** [comment]
my restvo project Podfile is auto generated by Capacitor, but here you go if it helps:
```
platform :ios, '11'
use_frameworks!

target 'App' do
  # Add your Pods here

  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorJitsiMeet', :path => '../../node_modules/capacitor-jitsi-meet'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end
```

**Comment by henry-wonder** [comment]
I actually don't have mac and i followed this tutorial to build for iOS https://medium.com/dev-genius/ionic-capacitor-from-app-to-ios-ipa-without-a-mac-9b8616900528

Here is my podfile looks like:

`platform :ios, '11.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Add your Pods here
  
  # Automatic Capacitor Pod dependencies, do not delete
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorJitsiMeet', :path => '../../node_modules/capacitor-jitsi-meet'
  pod 'CordovaPlugins', :path => '../capacitor-cordova-ios-plugins'
  # Do not delete
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end  
  end 
end
`
But I still got error when build for iOS ❌  ld: '/Users/runner/Library/Developer/Xcode/DerivedData/App-azlyibamtvkrbhfwntgmcwffjqtw/Build/Products/Release-iphoneos/Capacitor/Capacitor.framework/Caacitor' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file '/Users/runner/Library/Developer/Xcode/DerivedData/App-azlyibamtvkrbhfwntgmcwffjqtw/Build/Products/Release-iphoneos/Capacitor/Capacitor.framework/Capacitor' for architecture arm64

Any advice?

**Comment by calvinckho** [comment]
You need to disable bitcode for this target. I have not used a PC to build iOS app so can't advice you on how.
