### ISSUE TITLE
Ionic + Listeners

### ISSUE THREAD

**Issue by aguilalibre** [calvinckho/capacitor-jitsi-meet#41]
Probably is me the one whom did not find the right way to do this, but here goes my question... I would like to use a listener to record the time when somebody enters a conference and leaves a conference. Is tilt possible to use listeners with this plugin? By the way, I'm using Ionic 5.

Thank you!

**Comment by calvinckho** [comment]
Hi @aguilalibre, yes I would be happy to assist you with this. In the readme, you see I have the onConferenceJoined and onConferenceLeft handlers documented. So you can use them as follow:

// join call using Jitsi Plugin
const result = await Jitsi.joinConference({
   roomName: 'room1', // room identifier for the conference
   url: 'https://meet.jit.si' // endpoint of the Jitsi Meet video bridge,
   ...
});
window.addEventListener('onConferenceJoined', () => {
    this.startTime = new Date(); // log start time when joining call
});
window.addEventListener('onConferenceLeft', () => {
  // calculate total call time in second
   const callTimeInSec = Math.ceil((new Date().getTime() - this. this.startTime.getTime()) / 1000); // convert from ms to sec, and then round it up to sec.
   console("total call time is: ", callTimeInSec);
});
