### ISSUE TITLE
Leave conference and option to change call-integration.enabled and JMCallKitProxy.enabled

### ISSUE THREAD

**Issue by creativearish** [calvinckho/capacitor-jitsi-meet#43]
Hi,

I was looking for a way to implement jitsi in one of our Capacitor + Ionic project. And this plugin is amazing, Thanks @calvinckho .
But the only thing which was not there was implementation of ringing UI to accept or reject the call whenever a call arrives. I tried to accomplish that by using cordova-call for showing accept/reject call UI. But was facing the problem because Jitsi Meet were also using callkit and it was conflicting with cordova-call, I was not able to capture onHangup event of cordova.

After some research I couldn't find the answer, so I updated the plugin's native code to disable the call-integration. But then after hanging-up cordova call I was not able to leave the conference (jitsi end call button have to be tapped again after terminating call from native UI). So I added a method to leave the conference.

I've created a PR for leaveConference function and an input option to change value for 'call-integration.enabled' and 'JMCallKitProxy.enabled' (which is changed by setFeatureFlag). It is only for iOS at the moment.

Please review it and please pardon me if I made any mistake in code as I don't know anything about swift language. Your help for this would be greatly appreciated.

Thanks.

**Comment by calvinckho** [comment]
Thanks @creativearish. This is exciting. I will take a look later today and get back to you.

**Comment by calvinckho** [comment]
#44 I have expanded on your PR to include Android as well. Thanks for your great work!

**Comment by calvinckho** [comment]
@creativearish I released the beta version that has your PR included. Can you test out the 1.5.9@beta.2 version? 
also, I checked the flag and it seems that JMCallKitProxy.enabled is no longer used. The new flag is call-integration.enabled.

**Comment by creativearish** [comment]
@calvinckho Great to see your swift response, I've checked it and on iOS it is working great, but in android it was throwing an error for "receiver" related issue in Jitsi.java file. I've tried a solution and so far it is working, I've pushed it on my forked repo, commit - [7f5e7be](https://github.com/creativearish/capacitor-jitsi-meet/commit/7f5e7be238c36ce353ec46e2d53e880e17b6db73). Please review it and merge it for upcoming version.

Thanks, this plugin is great.

BTW when are you planning to launch new version? I am very curious for that. I am also thinking to bring manual methods like mute/unmute, camera on/off etc.

**Comment by calvinckho** [comment]
@creativearish thanks for catching the bug! I just applied your fix and released it in 1.5.9. 

and you, you are welcome to add new manual methods. I see in the documentation that both iOS and Android SDKs support muting audio now. I don't see any support for camera on/off yet. 

android:
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-android-sdk#set_audio_muted

iOS:
https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#setaudiomuted
