### ISSUE TITLE
Error bulid in android

### ISSUE THREAD

**Issue by Kcamplone** [calvinckho/capacitor-jitsi-meet#46]
hi there!!! I installed last version on another project 1.5.10 and when i build in android i m getting this error:

Could not find org.jitsi.react:jitsi-meet-sdk:3.3.0.
Required by:
    project :capacitor-jitsi-meet

thanks for your help!

**Comment by calvinckho** [comment]
@Kcamplone were you able to get it to work with 1.5.9?

I installed 1.5.10 and it is working fine on my samsung S7. 

I just released 1.5.11 using the 3.4.0 SDK. can you try to install it and see if it works?

**Comment by calvinckho** [comment]
@Kcamplone since this is an installation question, I am closing it for now. If you tried 1.5.12 and have issue again, you can reopen this.
