### ISSUE TITLE
Hide some features in mobile sdk 

### ISSUE THREAD

**Issue by said15904** [calvinckho/capacitor-jitsi-meet#55]
Hi,
I have some difficulty to hide lobby mode and mute (audio, video) for all participants
i try this setFeatureFlag(“lobby-mode.enabled”, withBoolean: false ) for lobby mode but not working
and for mute everyone i don’t see any features to configure that.
Thank you.

**Comment by calvinckho** [comment]
Hi @said15904, based on the official documentation, only the iFrame API supports toggle lobby mode: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe#togglelobby. 

The mobile API feature flags do not yet support it: https://jitsi.github.io/handbook/docs/dev-guide/mobile-feature-flags

As for muting everyone, it can be done on the UI level. See the attached screenshot for the mobile UI and Embedded iFrame UI.

![IMG_6016](https://user-images.githubusercontent.com/23274587/124045918-9ebe7a00-d9c5-11eb-9045-65dfe3d282a8.PNG)
![Screen Shot 2021-06-30 at 5 06 05 PM](https://user-images.githubusercontent.com/23274587/124045934-a5e58800-d9c5-11eb-8eda-f60c0e58f5a2.png)

But I don't think it can be configured programmatically: https://jitsi.github.io/handbook/docs/dev-guide/mobile-feature-flags

**Comment by said15904** [comment]
Thank you for your response,
Ok for lobby mode, but for muting everyone i want hide it not show it because i see in your screenshot exists all the time.
Thank you

**Comment by calvinckho** [comment]
Hi @said15904, okay I understand that you want to hide both the lobby mode button and the "mute all" button from the mobile secondary menu.

Your team will need to [modify the source code and compile your own Jitsi mobile SDK](https://github.com/calvinckho/capacitor-jitsi-meet/issues/37#issuecomment-765033111).

It requires setting up your local machine and is quite labor-intensive. I offer my service to modify and compile the Jitsi mobile SDKs for a fee. If you want my help you can @[DM](mailto:ch235@cornell.edu) me.
