### ISSUE TITLE
Update SDK in Ionic App using Capacitor-jitsi-meet

### ISSUE THREAD

**Issue by elhanid** [calvinckho/capacitor-jitsi-meet#56]
Hello,

I’m on an Ionic 5 App using capacitor-jitsi-meet to integrate JitsiMeet. It works very well, thanking @calvinckho .

Currently capacitor-jitsi-meet uses SDK version 3.5.0

My question is how updating / upgrading the SDK version 3.5.0 to —> 3.6.0. (for both android and ios) ?

I am not on the native and I want your help …

My thanks in advance.

**Comment by calvinckho** [comment]
Hi @elhanid, I upgraded the plugin to use 3.6.0 in capacitor-jitsi-meet@1.5.14-beta.0 on npm. Can you test it and let me know if it works okay? If so, I'll publish as production release 1.5.14.

**Comment by calvinckho** [comment]
@elhanid 1.5.14 is published as a production release.
