### ISSUE TITLE
[Question] How to enable picture in picture mode in ios

### ISSUE THREAD

**Issue by vphutane27** [calvinckho/capacitor-jitsi-meet#58]
Currently, on IOS we are not able to minimize the call.
Also on android, I am able to see a small down chevron to minimize but doesn't work

**Comment by calvinckho** [comment]
Jitsi Meet SDK does not currently implement native Picture-in-Picture on iOS. If desired, apps need to implement non-native Picture-in-Picture themselves and resize JitsiMeetView. See the official SDK documentation for more info: https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk#picture-in-picture
