### ISSUE TITLE
64 Bit Play Console Rejection

### ISSUE THREAD

**Issue by Taylorsuk** [calvinckho/capacitor-jitsi-meet#6]
I had some issues getting the Google Play store to accept this build. I note there is information on 32/64 bit architecture in the Android section. However in order for Google to allow rollout I had to edit the proposed line of `build.grade` from:

```
ndk {
   abiFilters "armeabi-v7a", "x86"
}
```
to 
```
ndk {
   abiFilters 'armeabi-v7a','arm64-v8a','x86','x86_64'
}
```
If I am brutally honest, I don't know the full details of why this fixed things, however it did for me.

**Comment by calvinckho** [comment]
thanks @Taylorsuk. Android SDK 2.2.2 is fully 64-bit so no need to turn on 32 bit architecture anymore. You can just remove the entire ndk property from defaultConfig.
