### ISSUE TITLE
sdk customization

### ISSUE THREAD

**Issue by timmyrosen** [calvinckho/capacitor-jitsi-meet#64]
Hi!

First of all, thanks for an amazing plugin!

I recently updated my app to Capacitor 3 and with it your plugin as well.
I noticed it came with a few UI modifications, a few too many for my need in fact.

If I want to remove a few options in the UI, could you assist me in that?

Kind regards!

**Comment by calvinckho** [comment]
Hi @timmyrosen, I would be happy to help. You can DM me [here](mailto:ch235@cornell.edu).

If you can let send me the UI customization specs (with screenshots), and also your target mobile platforms (iOS, Android), I can respond with a quote and the estimated delivery time. I just finished a big project so I have time to work on your project this week.
