### ISSUE TITLE
Swift Compiler error on Version 11.4 (11E146)

### ISSUE THREAD

**Issue by Taylorsuk** [calvinckho/capacitor-jitsi-meet#7]
Thank you so much for this plugin @calvinckho, it's been amazing to use and opened up a whole new avenue of business for my app. Unfortunately good old Apple has ruined the fun after Xcode upgraded today to Version 11.4 (11E146) and I'm now getting the following errors when building. Apologies for the image, however there is way too much to convey in code. 

<img width="1445" alt="Screenshot 2020-03-25 at 21 43 39" src="https://user-images.githubusercontent.com/852767/77588490-dea0d280-6ee1-11ea-84c2-f546d82caa84.png">

**Comment by calvinckho** [comment]
@Taylorsuk I will take a look and get back to you.

**Comment by Taylorsuk** [comment]
Thank you! At the moment I am downloading 7gb of Xcode 11.3.1 to try and get a successful build to ship a feature 😬

**Comment by calvinckho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5389#issue-587688251

**Comment by calvinckho** [comment]
https://github.com/jitsi/jitsi-meet/issues/5389#issue-587688251

**Comment by Boby** [comment]
brings my attention based on the readme, does this still applicable for ionic ios hybrid apps? @calvinckho

**Comment by Taylorsuk** [comment]
@Boby yes, you’re still going to be doing your build in Xcode. My comment above still stands, using an older version of Xcode is my solution until fixed.

**Comment by Boby** [comment]
@Taylorsuk this assume I can implement and still make use of this? :) I am on xcode 11.3(11C29)

**Comment by Taylorsuk** [comment]
11.3.1 (11C505) is the working version for me. 

Best thing to do is give it a go. As for the plugin! Amazing! It’s been incredible to work with, certainly worth navigating Apple’s moving goalposts.

**Comment by Boby** [comment]
@Taylorsuk strange on the ios app the app shutdown when trying to access the meeting?

**Comment by Taylorsuk** [comment]
@Boby I've replied to your other thread here: https://github.com/calvinckho/capacitor-jitsi-meet/issues/10

**Comment by calvinckho** [comment]
@Boby which Capacitor version are you using? Currently only 1.x is supported.

**Comment by Boby** [comment]
@calvinckho I am using capacitor 2, and android was working before... anyway we can upgrade this?

**Comment by calvinckho** [comment]
1.3.9 is published which supports Capacitor 2, Xcode 1.3.1. 

If you have Xcode 1.4.1, you can try 1.4.0, which is also released. I don't have Xcode 1.4.1 so I can't test it yet. If you have Xcode 1.4.1+ please test it and let me know if it works. Thanks!
