### ISSUE TITLE
Need Sample App for Making New App with Plugin

### ISSUE THREAD

**Issue by complabs28** [calvinckho/capacitor-jitsi-meet#70]
Hello,
I am a Student and am new to Ionic Development. I am implementing an app with this plugin to join meetings with Jitsi meet SDK. I copy your usage in the [README.md](https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/README.md#usage) File and paste it into my code in `Meet.tsx` file. I am using the `@ionic/react` Plugin for creating the app. But it shows errors and cannot build my app. can you provide me with a sample app to see what's wrong?

**Comment by calvinckho** [comment]
I just created a demo react app for this purpose: https://github.com/calvinckho/react-capacitor-jitsi-meet-sample. Since this is not a bug but a general question, don't mark it as Critical next time but use the 'question' label instead.

**Comment by complabs28** [comment]
I got an error in Android Studio Before Running the App <br> ![image](https://user-images.githubusercontent.com/86196753/153119395-671a50f9-a9af-4f0c-841f-2c779b2cd471.png)

**Comment by calvinckho** [comment]
I just added some missing files.
