### ISSUE TITLE
Dl bintray down

### ISSUE THREAD

**Issue by gigallo** [calvinckho/capacitor-jitsi-meet#73]
Hi

Trying to build the library in android studio an ssl error is returned by bintray ssl certificate:
https://dl.bintray.com/ionic-team/capacitor/org/jitsi/react/jitsi-meet-sdk/3.4.0/jitsi-meet-sdk-3.4.0.pom

any idea for alternatives?

Thanks

**Comment by calvinckho** [comment]
can you copy and paste a detailed log of the error?
