### ISSUE TITLE
iOS Pod set Enable Bitcode = "NO"

### ISSUE THREAD

**Issue by polfernandez** [calvinckho/capacitor-jitsi-meet#74]
Every new build for iOS platform, the step _6.ii Pods -> Targets -> CapacitorJitsiMeet -> Build Settings -> Enable Bitcode -> No_
Needs to be set manually.
It would be nice to configure the Pods file as mentioned in this [documentation](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-ios-sdk). 

`config.build_settings['ENABLE_BITCODE'] = 'NO'`

Thus, for new builds the build settings configuration is already stored.

**Comment by cyril-colin** [comment]
Hello,

In my Podfile I use this code:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
  if target.name == 'CapacitorJitsiMeet' || target.name == 'CapacitorJitsiMeet-Plugin'
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
  end
end
```

Once commited, every one who clone the project will have this setting setted to "NO" automatically.

Hope this helps

**Comment by polfernandez** [comment]
Hi, I guess that should do the trick. 
However, is it possible to set that somewhere using the Capacitor plugin from the master branch? 
I've tried to add these lines inside the node_modules/capacitor-jitsi-meet/ios/Plugin/Podfile and it doesn't work. Still have to change the ENABLE_BITCODE to 'NO' every ios build.

Thanks

**Comment by cyril-colin** [comment]
You should put that code in your `ios/App/Podfile` file. Never in a node_modules ;)

**Comment by calvinckho** [comment]
@cyril-colin's method works well. I have added her instructions in the the iOS README.md.
