### ISSUE TITLE
PIP in app

### ISSUE THREAD

**Issue by Pontalti-M** [calvinckho/capacitor-jitsi-meet#83]
Hi, 

we are currently implementing this plugin into our app, that also allows users to chat out of the plugin.
If a user is in a meeting can't go to the chat section expect if he closes the app ( in this case the video-meeting shrinks ) and reopens it.
There is any possibility to have the PIP function without closing the app? 

Thanks

**Comment by calvinckho** [comment]
Is it for Android or for iOS?

**Comment by Pontalti-M** [comment]
It's for both.
Thanks

**Comment by calvinckho** [comment]
https://user-images.githubusercontent.com/23274587/191375994-5dfb6505-c008-4354-8469-8bc72e5f8ee0.mp4

@Pontalti-M I don't understand your question. In Android, I am able to access the chat without closing the app or shrinking the video conference, as shown in the demo video.

**Comment by Pontalti-M** [comment]
@calvinckho the chat that we are using is not the jitsi chat, it's an external chat in the app. There is any possibility to shrink the video conference and stay in the app?

Thanks

**Comment by calvinckho** [comment]
Yes, it is possible, as demonstrated [here](https://ds.ivr.solutions/media/pip_demo.mp4). 

May I know which Capacitor version do you currently run? (Capacitor 2, 3, or 4)

As the author of this plugin, I also offer my consultation service to help developers implement the PIP mode using my plugin. [DM](mailto:ch235@cornell.edu) me if you want to learn more.
