### ISSUE TITLE
dosc(ios): new step needed for Xcode 14

### ISSUE THREAD

**Issue by abennouna** [calvinckho/capacitor-jitsi-meet#84]
Thanks for the great plugin!

Starting with Xcode 14, CODE_SIGNING_ALLOWED of resource bundle is set to YES by default, while it's NO in Xcode 13.x: https://developer.apple.com/forums/thread/708659

There seems to be, at least, a working solution, and two workarounds:

1. **working solution:** disable code signing on the `CapacitorJitsiMeet-Plugin`target
2. **workaround 1:** configure the development team on that target
3. **workaround 2:** use Xcode 13

Both the solution and the workaround worked in my case, and can be both automated via `Podfile`. However:

1. there does not seem to be a consensus on the approach, and the potential consequences of each solution
2. potential issue with the **workaround 1**: there's a reported app submission rejection: https://github.com/CocoaPods/CocoaPods/issues/11402#issuecomment-1258608914
3. potential issue with the working solution: there could be conflicting provisioning settings: https://forums.swift.org/t/xcode-14-beta-code-signing-issues-when-spm-targets-include-resources/59685

**Comment by calvinckho** [comment]
Hi @abennouna, thanks for raising this issue during the build process in Xcode 14. Do you have any update on a recommended solution? I'll be glad to update the readme.

**Comment by abennouna** [comment]
As far as I know, there does not seem to be a consensus, or an official recommendation from Apple.
I personally tested both workarounds mentioned, and didn't face build or archive problems. I have et to deploy to the store to see what happens.

**Comment by calvinckho** [comment]
I will close this for now. If new info can be added to the discussion, I'll be happy to reopen this issue. Thanks @abennouna for looking into this.
