### ISSUE TITLE
Default NPM installation version still 2.3.0

### ISSUE THREAD

**Issue by CharlieJ213** [calvinckho/capacitor-jitsi-meet#85]
Hello, I've just tried running `npm install capacitor-jitsi-meet@latest` and run into a dependency error with Capacitor v4 installed.

Running `npm install capacitor-jitsi-meet@3.0.0` fixed the error as I noticed the `@latest` tag was trying to install v2.3.0 which only has support for Capacitor v3.

Thought it was worth mentioning

**Comment by calvinckho** [comment]
Thanks @CharlieJ213. The latest tag is now added to @3.0.1.
