### ISSUE TITLE
Screen sharing is not working between web and mobile

### ISSUE THREAD

**Issue by SaranyaVenu20** [calvinckho/capacitor-jitsi-meet#86]
Hi,
Thank u for the plugin. I am facing some issues like when I share my screen from the web, the shared screen is not visible to the mobile users. Could u please help me out.

**Comment by calvinckho** [comment]
Can you provide more info on the mobile device and the version of the plugin used?

**Comment by SaranyaVenu20** [comment]
Hi, Thank you for your reply. Mobile device is Android 11 and capacitor 3

**Comment by calvinckho** [comment]
Are you hosting your own video bridge or are you using jitsi's bridge?

**Comment by SaranyaVenu20** [comment]
Hi, I am using jitsi bridge only. Could you please help me.


Thank you


With Best Regards,
Saranya V

**Comment by calvinckho** [comment]
I tested screensharing from web to [android (capacitor-jitsi-meet@3.0.1, uses Jitsi SDK 6.1.0)](https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/CHANGELOG.md#300-2022-09-20) and it is working fine. [Capacitor 3 version of the plugin](https://github.com/calvinckho/capacitor-jitsi-meet/blob/master/CHANGELOG.md#230-2022-09-15) is a bit dated now as it uses Jitsi SDK 5.1.0. You should upgrade to capacitor-jitsi-meet@3.0.1 (the version I tested and worked) and try again.

**Comment by SaranyaVenu20** [comment]
Hi
Thank you for your reply. I will try this and let you know.

**Comment by calvinckho** [comment]
Since it is working in the latest version, I will close this for now. Feel free to reopen it if the issue occurs in the future.
