### ISSUE TITLE
its is not working ionic 6 

### ISSUE THREAD

**Issue by AnshuEss** [calvinckho/capacitor-jitsi-meet#88]

**Comment by calvinckho** [comment]
Please provide more info and console log.

**Comment by AnshuEss** [comment]
window.addEventListener('onConferenceJoined', () => {
    // do things here
});

(property) AppComponent.window: any
Unexpected keyword or identifier.ts(1434)
Unexpected token. A constructor, method, accessor, or property was expected.ts(1068)

**Comment by calvinckho** [comment]
I am not able to reproduce the error. I need more info about your dev environment. Where do you see this error? Xcode? Android Studio? Your IDE? What version of capacitor are you using? What version of the plugin?

**Comment by calvinckho** [comment]
For folks searching this issue, I personally do not see a problem with the plugin working in Ionic 6. It deploys and runs fine on both iOS and Android devices. I will close this for now. If @AnshuEss can provide more debugging info, I'd be happy to reopen it.
