### ISSUE TITLE
Update to Jitsi Meet SDK 7

### ISSUE THREAD

**Issue by gianlucapinna83** [calvinckho/capacitor-jitsi-meet#89]
Hi,

I'm using JitsiMeet with the self-hosting soloution, and after last upgrade ( server side), I've an issue usign your plugin from an Ionic App: output video is down.
 
I've tried a conference between web ( using last web sdk) and Ionic app ( using sdk 6.0.1): on the mobile I can see my camera and other partecipants camera (in), instead web side I don't see the video from mobile ( audio is ok).

I suppose it's something linked to the JitsiMeetSdk version, is it possible to try the plugin with the last JitsiMeet SDK ? 

Thanks a lot!

**Comment by calvinckho** [comment]
I have committed a version using SDK 7.0.1. You can install using: npm i git+ssh://git@github.com:calvinckho/capacitor-jitsi-meet#capacitor-4

**Comment by gianlucapinna83** [comment]
It works also for me!
Thank you very much for your quik reply
