### ISSUE TITLE
Android / Not finishing call after leaving the meeting

### ISSUE THREAD

**Issue by carlos2712** [calvinckho/capacitor-jitsi-meet#9]
Hi, I'm running the plugin on different Android Emulators ( different versions)  after leaving the meeting on Android R looks like  the plugin it not closing the call and if I try to connect into another meeting session the app it's displaying  the following message : 

![Android_Emulator_-_Pixel_2_API_R_5554](https://user-images.githubusercontent.com/37664806/81744347-16071680-9471-11ea-88b3-39110264ab2d.png)

![Android_Emulator_-_Pixel_2_API_R_5554](https://user-images.githubusercontent.com/37664806/81744672-82821580-9471-11ea-8f7b-f86831027e07.png)

I'm running IONIC-react with capacitor 2.0 

All the rest of the Android versions are working correctly. 

Let me know if I can provide something or help to solve this issue. 

Thanks!

**Comment by calvinckho** [comment]
sorry for the delayed response. A temp solution is downgrade to capacitor 1.x (the current plugin does not support Capacitor 2.0 yet). I'm working on upgrading the plugin to support Capacitor 2.0 but it will take me some time.

**Comment by calvinckho** [comment]
1.3.9 is published which supports Capacitor 2, Xcode 1.3.1. 

If you have Xcode 1.4.1, you can try 1.4.0, which is also released. I don't have Xcode 1.4.1 so I can't test it yet. If you have Xcode 1.4.1+ please test it and let me know if it works. Thanks!
