### ISSUE TITLE
Error when opening Jitsi Android

### ISSUE THREAD

**Issue by jofftiquez** [calvinckho/capacitor-jitsi-meet#90]
> Failed to open file '/data/data/org.my.package/code_cache/.overlay/base.apk/assets/sounds/reactions-surprise.mp3': No such file or directory

It seems this causes jitsi to crash

![image](https://user-images.githubusercontent.com/8638243/230806434-d41de656-65a9-4e1b-bbe9-c81d7ca2951a.png)

**Comment by calvinckho** [comment]
Hi @jofftiquez, I am sorry I am unable to help you debug your crashed app. I tested it and was able to build and open Jitsi Android when I built my test app. You need to provide more console log and build info of the issues you encountered, otherwise it is very difficult to help you.

**Comment by jofftiquez** [comment]
> Hi @jofftiquez, I am sorry I am unable to help you debug your crashed app. I tested it and was able to build and open Jitsi Android when I built my test app. You need to provide more console log and build info of the issues you encountered, otherwise it is very difficult to help you.

Hey man, no problem at all. I'll provide mo info when I get back to this project. It has been paused at the moment. Thank you!
