### ISSUE TITLE
app:processDebugResources FAILED run android error capacitor plugin

### ISSUE THREAD

**Issue by LuisDiaz-ipsilon** [calvinckho/capacitor-jitsi-meet#94]
I followed the installation steps but when trying to build I have the following errors:
I leave the complete log as [err.txt](https://github.com/calvinckho/capacitor-jitsi-meet/files/13946852/err.txt)

* What went wrong:
Execution failed for task ':capacitor-jitsi-meet:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':capacitor-jitsi-meet:debugCompileClasspath'.
   > Could not find org.jitsi.react:jitsi-meet-sdk:8.6.0.
     Required by:
         project :capacitor-jitsi-meet

**Comment by calvinckho** [comment]
Have you done 'npx cap update' before you build the Android app?

**Comment by gasci** [comment]
You need to clean your Podfile.lock file first if you installed a previous version. @LuisDiaz-ipsilon

**Comment by LuisDiaz-ipsilon** [comment]
Yes execute "npx cap sync" and "npx cap update" before and after opening the project in Android Studio. I started with this project a few hours ago. @calvinckho

**Comment by LuisDiaz-ipsilon** [comment]
I am currently developing for Android, @gasci Thank you

**Comment by calvinckho** [comment]
![Screenshot 2024-01-18 at 3 13 32 PM](https://github.com/calvinckho/capacitor-jitsi-meet/assets/23274587/e4dadf99-4e3a-4122-a8fe-3cc7cbb4b0be)

Here is the build log for my app, as you see it builds successfully. More info is needed to help you debug your issue. But it seems that your plugin wasn't synced/updated correctly.

**Comment by LuisDiaz-ipsilon** [comment]
I was able to run the plugin in app ionic react. Thanks
