### ISSUE TITLE
Log in as a moderator pop up

### ISSUE THREAD

**Issue by gasci** [calvinckho/capacitor-jitsi-meet#95]
With the update SDK 8.6.0, we are forced to see the option to log in or wait for the moderator via the phone SDK. Is there a way to disable it. It didn't exist in 8.1.2.

I couldn't find any option here:
```
https://github.com/jitsi/jitsi-meet/blob/master/config.js
https://github.com/jitsi/jitsi-meet/blob/master/react/features/base/flags/constants.ts
```

**Comment by calvinckho** [comment]
you want to have your own authentication you have a couple of choices:

1. Run your own backend: this has the utmost flexibility
2. Use JaaS: you can use whatever auth you want and then get a JaaS token to drop users into meetings

See here for the discussion on the [latest requirement by Jitsi](https://github.com/jitsi/jitsi-meet/issues/14017) and their fair use terms of service.
