### ISSUE TITLE
Builds constantly require re-signing the Plugin code

### ISSUE THREAD

**Issue by viking2917** [calvinckho/capacitor-jitsi-meet#96]
(Thanks for this plugin, btw!)

After installing the plugin into an Ionic iOS App, each time I build from the command line, I receive the following error:

`....../ios/App/Pods/Pods.xcodeproj: error: Signing for "CapacitorJitsiMeet-Plugin" requires a development team. Select a development team in the Signing & Capabilities editor. (in target 'CapacitorJitsiMeet-Plugin' from project 'Pods')`

 I then have to re-set the Team Signature for the plugin by hand inside xCode.

xCode 15.1
iOS Device running: 17.2.1
Ionic CLI                     : 7.1.1 (/Users/markwatkins/.nvm/versions/node/v18.16.0/lib/node_modules/@ionic/cli)
Ionic Framework               : @ionic/angular 7.6.1
Capacitor CLI      : 5.6.0
@capacitor/core    : 5.5.0
@capacitor/ios     : 5.5.0

This appears somewhat related to closed issue [84](https://github.com/calvinckho/capacitor-jitsi-meet/issues/84), but my problem is slightly different. 

As per that issue, I go to the plugin under targets and set the Team to the same Team signing as I use for my app. Everything then runs ok, so long as I run from xCode. I can start / join conferences no problem. 

But as soon as I compile from the command line, the Signing gets re-set and I have to manually specify it again. 

This prevents running a 'live reload' on the app, as the command 

`ionic capacitor run ios -l --external` 

croaks with the same error and I cannot correct it except by going to xCode. 

Any idea what I might be doing wrong? Alternatively, how do I get the signing to stay unchanged?

Two observations which may or may not be relevant:

1) The CapacitorJitsiMeet-Plugin target has a blue icon - all my other Pods targets have orange icons. I do not know the significance of the color or whether it matters, but it is the only blue one.
2) The plugin Bundle identifier is set to org.cocoapods.Plugin, which seems generic and perhaps not specific to this plugin?

**Comment by calvinckho** [comment]
sorry I always run from Xcode so this has never been an issue for me.  I do not know how to prevent the code signing from getting reset for those running from the command line as this is not my build environment.

**Comment by calvinckho** [comment]
@viking2917  I am closing this for now . Feel free to reopen it if you found a solution.
