### ISSUE TITLE
Suggested Documentation Additions - meet.jitsi.si not suitable for production use

### ISSUE THREAD

**Issue by viking2917** [calvinckho/capacitor-jitsi-meet#97]
meet.jitsi.si is no longer intended for production use, and meetings created with the API with that server are limited to five minutes. I would suggest an addition to the documentation to guide developers to the correct setup. If this is desired, I could submit a PR with the following addition to the Readme.

### Production Jitsi Server Configuration

_https://meet.jitsi.si_ is designed for testing purposes when used with the Jitsi API. According to Jitsi, it is not intended for production use. Meetings created with this server will be limited to 5 minutes. In addition, also note that fully anonymous meetings are no longer possible under the Jitsi Meet API when using this server (see authentication post below).

Please note that the examples here use `url: 'https://meet.jit.si'` for the Jitsi server, but this server is [only intended for test usage](https://jitsi.org/api/). 

For production usage, one should either use a [self-hosted server](https://jitsi.github.io/handbook/docs/devops-guide/), or use JaaS, Jitsi-as-a-Service. This latter service can be found at [https://jaas.8x8.vc/](https://jaas.8x8.vc/).

To use JaaS in this capacitor version use: `url: 'https://8x8.vc/'`.

when initializing via the start() function, and in the web-based [iFrame API](https://jitsi.github.io/handbook/docs/dev-guide/dev-guide-iframe), you will need to load the iFrame javascript from 

```
https://8x8.vc/libs/external_api.min.js'
```

**The usage of JaaS requires an account and a payment method**. At the time of this writing, 25 users are permitted per month for free, and after that one must pay. 

Further information:
https://jitsi.org/api/
https://jitsi.org/blog/authentication-on-meet-jit-si/
https://community.jitsi.org/t/authentication-on-meet-jit-si/125922/53

**Comment by calvinckho** [comment]
@viking2917 Yes, please create a PR. Thank you for typing it up. I think it is time that we make this clear so new users are aware of the change.

**Comment by viking2917** [comment]
Create PR #98. Happy to change wording as desired.

**Comment by calvinckho** [comment]
#98 merged and closing this.
